# Generated by Django 5.0.3 on 2024-04-01 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('administration_method', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier_name', models.CharField(max_length=100)),
                ('feeding_time', models.DateTimeField()),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
