# Generated by Django 5.0.3 on 2024-04-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='quantity_bought',
            field=models.DecimalField(decimal_places=2, default='10 Kg', max_digits=10),
            preserve_default=False,
        ),
    ]
