# Generated by Django 5.0.3 on 2024-04-01 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0001_initial'),
        ('birds', '0001_initial'),
        ('livefarm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='birdsstock',
            name='invoice_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='livefarm.financemodel'),
        ),
        migrations.AddField(
            model_name='birdsstock',
            name='pen_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Farm.poultryhouse', to_field='pen_number'),
        ),
        migrations.AddField(
            model_name='mortalitycull',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mortalitycull',
            name='pen_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Farm.poultryhouse', to_field='pen_number'),
        ),
        migrations.AddField(
            model_name='penhouse',
            name='auth_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
