# Generated by Django 5.0.3 on 2024-04-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Workers', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Staff',
        ),
    ]
